name: get_multipart_request
description: Package para obter os dados do formulário de uma requisição multpart
version: 1.0.0

publish_to: none

environment:
  sdk: ^3.5.3

dependencies:
  shelf: ^1.4.2
  http: ^1.1.0
  mime: ^1.0.6
  http_parser: ^4.1.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  shelf_router: ^1.1.0
